### ISSUE TITLE
01_SafetyPlan_LaneAssistance_Template.docx

### ISSUE THREAD

**Issue by jainhitesh9998** [udacity/CarND-Functional-Safety-Project#2]
Conformation seems more appropriate than Confirmation used in the following text

Confirmation Measures

[Instructions: 
Please answer the following questions:

1.	What is the main purpose of confirmation measures?
2.	What is a confirmation review?
3.	What is a functional safety audit?
4.	What is a functional safety assessment?
]

**Comment by mvirgo** [comment]
**Confirmation Measures** are an official part of [ISO 26262](https://en.wikipedia.org/wiki/ISO_26262).
